name: wp3-solutions 

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '9.0.x',
          '11.0.x',
          '12.0.x',
          '13.0.x',
          '14.0.x',
          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Build for Eclipse
        run: |
          ./config.sh

      - name: Run Californium & ACE JUnit tests
        run: |
          ./test-californium.sh
          ./test-ace.sh --with-mysql
          ./code-coverage.sh

      - name: Deploy Jacoco code coverage reports to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ matrix.java-version == '8.0.x' }}
        with:
          clean: true
          folder: jacoco
          target-folder: reports
          branch: gh-pages


  docker:

    if: ${{ github.repository == 'sifis-home/wp3-solutions' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          architecture: x64
      -
        name: Prepare Dockerfiles and files for Contexts
        run: |
          ./build-for-docker.sh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image (Authorization Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsServer
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/authorization-server:latest
      -
        name: Build and push image (Group Manager)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreRsServer
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/group-manager:latest
      -
        name: Build and push image (Group OSCORE Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Client2
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/group-client:latest
      -
        name: Build and push image (Group OSCORE Server 1)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server4
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/group-server1:latest
      -
        name: Build and push image (Group OSCORE Server 2)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server5
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/group-server2:latest
      -
        name: Build and push image (Group OSCORE Server 3)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server6
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/group-server3:latest
      -
        name: Build and push image (CoAP Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase0Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/coap-server:latest
      -
        name: Build and push image (CoAP Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase0Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/coap-client:latest
      -
        name: Build and push image (EDHOC Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase4Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/edhoc-server:latest
      -
        name: Build and push image (EDHOC Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase4Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: false
          tags: sifishome/edhoc-client:latest

