name: wp3-solutions 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '9.0.x',
          '10.0.x',
          #'11.0.x',
          #'12.0.x',
          #'13.0.x',
          #'14.0.x',
          #'15.0.x',
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Build for Eclipse
        run: |
          ./config.sh
          
      - name: Run JUnit tests for ACE
        run: |
          cd ace
          mvn test
        
      - name: Run JUnit tests for Californium
        run: |
          cd californium-group-oscore
          mvn test
        
           
